start-balance: 100
kramp-price: 5000
# buy = cena nakupa, sell = cena prodaje (0 = ni mogoče)
items:
  COBBLESTONE: {buy: 2, sell: 0.5}
  STONE: {buy: 3, sell: 1}
  DIRT: {buy: 1, sell: 0.2}
  OAK_LOG: {buy: 6, sell: 2}
  COAL: {buy: 15, sell: 5}
  IRON_INGOT: {buy: 40, sell: 15}
  GOLD_INGOT: {buy: 80, sell: 30}
  REDSTONE: {buy: 20, sell: 6}
  LAPIS_LAZULI: {buy: 20, sell: 6}
  DIAMOND: {buy: 250, sell: 100}
  EMERALD: {buy: 200, sell: 80}
  WHEAT: {buy: 5, sell: 1.5}
  BREAD: {buy: 12, sell: 4}
  COOKED_BEEF: {buy: 15, sell: 5}
